import fs from 'fs';
import assert from 'assert';
import crypto from 'crypto';
const src=fs.readFileSync('./apps-script/Central_Image_Queens_Seed_AutoLearn_V2.gs','utf8');
const a=src.indexOf('function normalizeImagePackTestLineageV1_()');
const b=src.indexOf('function evaluateImageTemplateTestsAndPromotionV4_()',a);
assert(a>=0&&b>a);
const fn=eval('('+src.slice(a,b).trim()+')');
const header=['TEST_ID','CANDIDATE_PACK_ID','TOTAL_SCORE','FAILURE_SIGNATURE','DRIVE_ID','RUN_ID','RESULT_ID','ACK_ID','DEDUPE_KEY','PARENT_TEMPLATE_ID','FIX_SIGNATURE'];
const rows=[header,['T_PASS','CAND_A',95,'','DRV_A','','','','','',''],['T_FAIL','CAND_B',40,'WRONG_TARGET','DRV_B','','','','','','']];
const sheet={getDataRange(){return{getValues(){return rows.map(r=>r.slice())}}}};
globalThis.IMAGE_LEARNING_TABS={TEST:'PACK_TEST_MATRIX'};
globalThis.IMAGE_LEARNING_V2_VERSION='TEST_V49';
globalThis.imgPackSheetV2_=()=>sheet;
globalThis.imgIndexV2_=h=>Object.fromEntries(h.map((x,i)=>[x,i]));
globalThis.imgSha256V2_=s=>crypto.createHash('sha256').update(s).digest('hex');
globalThis.imgSetV2_=(sh,row,idx,patch)=>{for(const [k,v] of Object.entries(patch))rows[row-1][idx[k]]=v};
let one=fn(); const snap=JSON.stringify(rows); let two=fn();
assert.equal(one.scanned,2); assert.equal(one.failuresPreserved,1); assert.equal(one.noScoreMutation,true);
assert.equal(rows[1][2],95); assert.equal(rows[2][2],40); assert.equal(rows[2][10],'WRONG_TARGET');
assert.equal(rows[1][8],'TEST|T_PASS'); assert(rows[1][9].startsWith('MMT_IMAGE_PACK_TEST_MATRIX_LIGHT_V1'));
assert.equal(JSON.stringify(rows),snap); assert.equal(two.dedupeStable,true);
console.log('PACK_TEST_LINEAGE_X2_PASS',JSON.stringify({one,two,passRun:rows[1][5],failFix:rows[2][10]}));