import fs from 'fs'; import assert from 'assert';
const src=fs.readFileSync('C:/Users/User/Documents/QueensLightPatch20260907/apps-script/Central_Image_Queens_Seed_AutoLearn_V2.gs','utf8');
const m=src.match(/function evaluateImageAssetSeedGateV2\(requestId\)\{.*?\}(?=\r?\n+function imageLearningHealthV2)/s); if(!m) throw new Error('gate fn not found');
const qh=['REQUEST_ID','QUEENS_ID','SEED_ID','TEMPLATE_ID','FEATURE_STATUS','TEMPLATE_STATUS','RIGHTS_ROLE','SPATIAL_STATUS','ASSET_CLASS','SPACE_TYPE','SOURCE_HASH','SOURCE_URL'];
const q=[qh,['REQ_A','Q_A','SEED_A','TPL_A','PASS_VERIFIED_FEATURE','TEMPLATE_CANDIDATE_X2_PENDING','USER_SUPPLIED_INTERNAL_REFERENCE','PASS_DRIVE_VISUAL_SPATIAL_QA','SPACE|FIXTURE','KITCHEN','E84E','https://a'],['REQ_B','Q_B','SEED_B','TPL_B','VERIFIED_GENERATED_OUTPUT_FEATURES_EXTRACTED','CANDIDATE_PENDING_X2','INTERNAL_GENERATED','VISUAL_SPATIAL_QA_PASS_CANDIDATE','SPACE|FIXTURE','KITCHEN','D3DF','https://b']];
const gh=['GATE_ID','REQUEST_ID','ASSET_ID','ASSET_CLASS','SPACE_ROLE','QUEENS_ID','QUEENS_VERIFIED','SEED_ID','SEED_VERIFIED','TEMPLATE_ID','TEMPLATE_VERIFIED','RIGHTS_PASS','SPATIAL_QA_PASS','X2_PASS','GENERATION_ALLOWED','FLOW_ALLOWED','BLOCK_REASON','LAST_GOOD','STATUS','NOTES','RUN_ID','RESULT_ID','ACK_ID','DEDUPE_KEY','PARENT_TEMPLATE_ID','FIX_SIGNATURE']; const g=[gh];
const sh=['SEED_ID','QUEENS_STATUS','STATUS']; const s=[sh,['SEED_A','DRIVE_VISUAL_SPATIAL_VERIFIED','REFERENCE_SEED_TEMPLATE_PENDING_X2'],['SEED_B','GENERATED_OUTPUT_DRIVE_VERIFIED','SEED_DRAFT_X2_TEMPLATE_PENDING']];
function sheet(data){return {getDataRange:()=>({getValues:()=>data}),getRange:(r,c,h,w)=>({setValues:rows=>{data[r-1]=rows[0].slice();}}),appendRow:row=>data.push(row.slice()),getLastRow:()=>data.length};}
global.IMAGE_LEARNING_TABS={QUEENS:'Q',ASSET_GATE:'G',SEED:'S'}; global.IMAGE_LEARNING_V2_VERSION='TEST'; global.Utilities={formatDate:()=> '20260907_175500'};
global.imgPackSheetV2_=n=>n==='Q'?sheet(q):sheet(g); global.imgMasterSheetV2_=()=>sheet(s); global.imgIndexV2_=h=>Object.fromEntries(h.map((v,i)=>[v,i])); global.imgSha256V2_=x=>'HASH'+x; global.imgIsSpatialClassV2_=x=>x.includes('SPACE');
const evaluateImageAssetSeedGateV2=eval('('+m[0]+')'); let out=evaluateImageAssetSeedGateV2(); assert.equal(out.checked,2); assert.equal(out.blocked,2); assert.equal(out.written,2); assert.equal(out.generationAllowed,false);
const gi=imgIndexV2_(gh),a=g.find(r=>r[gi.QUEENS_ID]==='Q_A'),b=g.find(r=>r[gi.QUEENS_ID]==='Q_B'); assert.equal(a[gi.SEED_VERIFIED],'Y'); assert.equal(a[gi.SPATIAL_QA_PASS],'Y'); assert.equal(a[gi.GENERATION_ALLOWED],'N'); assert.equal(a[gi.BLOCK_REASON],'ACTIVE_TEMPLATE|X2_PASS');
assert.equal(b[gi.SEED_VERIFIED],'N'); assert.equal(b[gi.SPATIAL_QA_PASS],'N'); assert.equal(b[gi.GENERATION_ALLOWED],'N'); assert.ok(b[gi.BLOCK_REASON].includes('SEED_VERIFIED')&&b[gi.BLOCK_REASON].includes('SPATIAL_QA'));
q[1][qh.indexOf('TEMPLATE_STATUS')]='ACTIVE_INTERNAL_TEMPLATE'; out=evaluateImageAssetSeedGateV2('REQ_A'); assert.equal(out.pass,1); assert.equal(out.blocked,0); assert.equal(out.generationAllowed,true); const a2=g.find(r=>r[gi.QUEENS_ID]==='Q_A'); assert.equal(a2[gi.GENERATION_ALLOWED],'Y'); assert.equal(a2[gi.X2_PASS],'Y');
console.log('ASSET_GATE_CHANGED_CONDITION_X2_PASS',JSON.stringify({initial:{blocked:2,A:a[gi.BLOCK_REASON],B:b[gi.BLOCK_REASON]},changed:{pass:out.pass,generationAllowed:out.generationAllowed}}));