#!/usr/bin/env python3
"""Build central SketchUp learning Seeds and output templates from a native manifest.

Input is generated by sketchup/ruby/central_skp_manifest_exporter.rb.
This tool never parses raw .skp bytes and never invents prices or dimensions.
"""

from __future__ import annotations

import argparse
import hashlib
import json
import re
from datetime import datetime, timezone
from pathlib import Path
from typing import Any, Dict, List

VERSION = "CENTRAL_SKP_SEED_BUILDER_V1_20260903"

ROOM_HINTS = {
    "주방": "KITCHEN",
    "거실": "LIVING",
    "안방": "MASTER_BEDROOM",
    "침실": "BEDROOM",
    "욕실": "BATHROOM",
    "화장실": "BATHROOM",
    "현관": "ENTRY",
    "드레스": "DRESS_ROOM",
    "서재": "STUDY",
    "사무": "OFFICE",
    "오피스": "OFFICE",
    "병원": "CLINIC",
    "소아과": "CLINIC",
    "상가": "COMMERCIAL",
    "근생": "COMMERCIAL",
}


def now_iso() -> str:
    return datetime.now(timezone.utc).astimezone().isoformat(timespec="seconds")


def stable_id(prefix: str, *parts: Any) -> str:
    raw = "|".join(str(p or "") for p in parts).encode("utf-8")
    return f"{prefix}_{hashlib.sha256(raw).hexdigest()[:16].upper()}"


def load_json(path: Path) -> Dict[str, Any]:
    with path.open("r", encoding="utf-8") as f:
        return json.load(f)


def dump_json(path: Path, payload: Any) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open("w", encoding="utf-8") as f:
        json.dump(payload, f, ensure_ascii=False, indent=2)


def infer_project_class(file_name: str) -> Dict[str, Any]:
    n = file_name.lower()
    out = {"building_type": "UNKNOWN", "area_pyeong": None, "location_tags": []}
    if "아파트" in n or any(x in n for x in ["래미안", "푸르지오", "아이파크", "주공", "파크리오"]):
        out["building_type"] = "APARTMENT"
    elif "빌라" in n:
        out["building_type"] = "VILLA"
    elif "오피스텔" in n:
        out["building_type"] = "OFFICETEL"
    elif "주택" in n or "하우스" in n:
        out["building_type"] = "HOUSE"
    elif any(x in n for x in ["오피스", "근생", "병원", "소아과", "골프"]):
        out["building_type"] = "COMMERCIAL"

    m = re.search(r"(\d{1,3})\s*평", file_name)
    if m:
        out["area_pyeong"] = int(m.group(1))

    for loc in ["강동", "성동", "송파", "서초", "강남", "남양주", "의정부", "구리", "용산", "중랑", "성북", "동대문", "하남", "양주", "수원", "별내", "다산", "평내", "호평", "잠실", "청담"]:
        if loc in file_name:
            out["location_tags"].append(loc)
    return out


def infer_room_types(manifest: Dict[str, Any]) -> List[str]:
    corpus = " ".join(
        [manifest.get("model", {}).get("file_name", "")]
        + [str(x.get("definition_name", "")) for x in manifest.get("components", [])]
        + [str(x.get("name", "")) for x in manifest.get("scenes", [])]
        + [str(x.get("name", "")) for x in manifest.get("tags", [])]
    )
    rooms = sorted({mapped for key, mapped in ROOM_HINTS.items() if key in corpus})
    return rooms or ["UNCLASSIFIED_ROOM"]


def verify_manifest(manifest: Dict[str, Any]) -> Dict[str, Any]:
    model = manifest.get("model") or {}
    bounds = model.get("bounds_mm") or {}
    unit = model.get("unit") or {}
    issues: List[str] = []
    if not manifest.get("qa", {}).get("content_extracted"):
        issues.append("CONTENT_NOT_EXTRACTED")
    for key in ("width", "depth", "height"):
        value = bounds.get(key)
        if not isinstance(value, (int, float)) or value < 0:
            issues.append(f"INVALID_BOUND_{key.upper()}")
    if not unit.get("length_unit_label"):
        issues.append("UNIT_UNKNOWN")
    return {
        "pass": not issues,
        "issues": issues,
        "status": "MANIFEST_QA_PASS" if not issues else "MANIFEST_QA_REVIEW",
    }


def component_seed_rows(model_id: str, manifest: Dict[str, Any]) -> List[Dict[str, Any]]:
    rows = []
    for comp in manifest.get("components", []):
        name = comp.get("definition_name") or "UNNAMED_COMPONENT"
        rows.append(
            {
                "seed_id": stable_id("SEED_SKP_COMPONENT", model_id, name),
                "seed_type": "FURNITURE_COMPONENT",
                "topic_id": name,
                "seed_text": f"SketchUp component {name}; quantity={comp.get('instance_count')}; bounds_mm={comp.get('bounds_mm')}",
                "feature_json": comp,
                "qa_status": "CONTENT_EXTRACTED_DIMENSION_QA_PENDING",
            }
        )
    return rows


def material_seed_rows(model_id: str, manifest: Dict[str, Any]) -> List[Dict[str, Any]]:
    rows = []
    for mat in manifest.get("materials", []):
        name = mat.get("name") or "UNNAMED_MATERIAL"
        rows.append(
            {
                "seed_id": stable_id("SEED_SKP_MATERIAL", model_id, name),
                "seed_type": "MATERIAL",
                "topic_id": name,
                "seed_text": f"SketchUp material {name}; color={mat.get('color_rgb')}; texture={mat.get('texture_filename')}",
                "feature_json": mat,
                "qa_status": "CONTENT_EXTRACTED_RIGHTS_QA_PENDING",
            }
        )
    return rows


def scene_seed_rows(model_id: str, manifest: Dict[str, Any]) -> List[Dict[str, Any]]:
    rows = []
    for scene in manifest.get("scenes", []):
        name = scene.get("name") or "UNNAMED_SCENE"
        rows.append(
            {
                "seed_id": stable_id("SEED_SKP_SCENE", model_id, name),
                "seed_type": "SCENE_CAMERA",
                "topic_id": name,
                "seed_text": f"SketchUp scene {name}; reusable for image/video camera planning after geometry QA.",
                "feature_json": scene,
                "qa_status": "CONTENT_EXTRACTED_CAMERA_QA_PENDING",
            }
        )
    return rows


def build_space_seed(model_id: str, manifest: Dict[str, Any]) -> Dict[str, Any]:
    model = manifest.get("model") or {}
    file_name = model.get("file_name") or model.get("title") or "unknown.skp"
    project = infer_project_class(file_name)
    rooms = infer_room_types(manifest)
    bounds = model.get("bounds_mm") or {}
    hard = {
        "unit": model.get("unit"),
        "model_bounds_mm": bounds,
        "metadata_dimensions_are_not_room_dimensions": True,
        "room_envelope_requires_viewer_or_geometry_segmentation": True,
    }
    return {
        "seed_id": stable_id("SEED_SKP_SPACE", model_id, file_name),
        "seed_type": "SPACE",
        "topic_id": f"{project['building_type']}_{project.get('area_pyeong') or 'NA'}",
        "room_type": rooms,
        "seed_text": (
            f"Native SketchUp space model {file_name}. Building={project['building_type']}; "
            f"area_pyeong={project.get('area_pyeong')}; model_bounds_mm={bounds}. "
            "Use native geometry as truth; derive room layout/clearance only after spatial QA."
        ),
        "feature_json": {"project": project, "rooms": rooms, "model": model},
        "hard_constraints": hard,
        "qa_status": "CONTENT_EXTRACTED_SPATIAL_QA_PENDING",
    }


def build_estimate_rules(manifest: Dict[str, Any]) -> Dict[str, Any]:
    return {
        "quantity_sources": ["model_bounds", "component_bom", "future_room_surface_segmentation"],
        "pricing_policy": "VERIFIED_PRICE_BOOK_ONLY",
        "no_price_guess": True,
        "bom": manifest.get("bom", []),
        "status": "QUANTITY_SEED_READY_PRICE_BOOK_OPTIONAL",
    }


def build_prompt_bundle(space_seed: Dict[str, Any], manifest: Dict[str, Any]) -> Dict[str, Any]:
    scenes = [x.get("name") for x in manifest.get("scenes", []) if x.get("name")]
    materials = [x.get("name") for x in manifest.get("materials", []) if x.get("name")]
    components = [x.get("definition_name") for x in manifest.get("components", []) if x.get("definition_name")]
    return {
        "schema_version": "SKP_PROMPT_BUNDLE_V1",
        "hard_constraints": space_seed.get("hard_constraints"),
        "geometry_prompt_order": [
            "PROJECT_AND_UNIT",
            "ROOM_ENVELOPE",
            "OPENINGS_AND_FIXED_POINTS",
            "FUNCTIONAL_ZONES",
            "CLEARANCE_AND_CIRCULATION",
            "COMPONENT_PLACEMENT",
            "MATERIALS_AND_TAGS",
            "SCENES_AND_CAMERAS",
            "OUTPUT_REQUIREMENTS",
        ],
        "known_components": components,
        "known_materials": materials,
        "known_scenes": scenes,
        "image_support": {
            "use": ["room_geometry", "camera_seed", "material_seed", "component_seed"],
            "rule": "render prompt must not override geometry truth",
        },
        "video_support": {
            "use": ["scene_seed", "camera_seed", "circulation_seed", "component_seed"],
            "rule": "shot continuity must preserve room topology",
        },
    }


def output_templates() -> List[Dict[str, Any]]:
    return [
        {"template_id": "SKPTPL_FLOORPLAN_V1", "output_type": "FLOORPLAN", "requires": ["SPACE", "ROOM_MAP", "OPENINGS"], "status": "SCHEMA_READY"},
        {"template_id": "SKPTPL_PERSPECTIVE_V1", "output_type": "PERSPECTIVE", "requires": ["SPACE", "CAMERA", "MATERIAL"], "status": "SCHEMA_READY"},
        {"template_id": "SKPTPL_ISOMETRIC_V1", "output_type": "ISOMETRIC", "requires": ["SPACE", "TAG", "CAMERA"], "status": "SCHEMA_READY"},
        {"template_id": "SKPTPL_VIDEO_SCENE_V1", "output_type": "VIDEO_SCENE", "requires": ["SCENE", "CAMERA", "CIRCULATION"], "status": "SCHEMA_READY"},
        {"template_id": "SKPTPL_ESTIMATE_V1", "output_type": "ESTIMATE", "requires": ["QUANTITY", "BOM"], "status": "SCHEMA_READY"},
        {"template_id": "SKPTPL_MATERIAL_LIST_V1", "output_type": "MATERIAL_LIST", "requires": ["MATERIAL", "SURFACE_OR_COMPONENT"], "status": "SCHEMA_READY"},
        {"template_id": "SKPTPL_FINISH_LIST_V1", "output_type": "FINISH_LIST", "requires": ["ROOM_MAP", "MATERIAL"], "status": "SCHEMA_READY"},
        {"template_id": "SKPTPL_MATERIAL_BOARD_V1", "output_type": "MATERIAL_BOARD", "requires": ["FINISH_LIST", "RIGHTS_VERIFIED_IMAGES"], "status": "SCHEMA_READY"},
        {"template_id": "SKPTPL_SCHEDULE_V1", "output_type": "PROCESS_SCHEDULE", "requires": ["TRADE_SCOPE", "QUANTITY", "DEPENDENCY"], "status": "SCHEMA_READY"},
        {"template_id": "SKPTPL_CLIENT_PROPOSAL_V1", "output_type": "CLIENT_PROPOSAL", "requires": ["VALIDATED_OUTPUTS"], "status": "SCHEMA_READY"},
    ]


def build(manifest: Dict[str, Any], source_path: Path) -> Dict[str, Any]:
    qa = verify_manifest(manifest)
    model = manifest.get("model") or {}
    file_name = model.get("file_name") or source_path.stem
    model_id = stable_id("SKPMODEL", model.get("local_signature"), file_name)
    space = build_space_seed(model_id, manifest)
    seeds = [space]
    seeds.extend(component_seed_rows(model_id, manifest))
    seeds.extend(material_seed_rows(model_id, manifest))
    seeds.extend(scene_seed_rows(model_id, manifest))

    for seed in seeds:
        seed.setdefault("model_id", model_id)
        seed.setdefault("file_id", None)
        seed.setdefault("project_id", None)
        seed.setdefault("rights_status", "SOURCE_RIGHTS_REVIEW_REQUIRED")
        seed.setdefault("created_at", now_iso())
        seed.setdefault("updated_at", now_iso())
        seed.setdefault("template_id", "MMT_SKETCHUP_SPATIAL_DESIGN_V1")

    return {
        "schema_version": "SKP_SEED_BUNDLE_V1",
        "builder_version": VERSION,
        "created_at": now_iso(),
        "source_manifest": str(source_path),
        "model_id": model_id,
        "manifest_qa": qa,
        "space_seed": space,
        "seeds": seeds,
        "estimate_rules": build_estimate_rules(manifest),
        "prompt_bundle": build_prompt_bundle(space, manifest),
        "output_templates": output_templates(),
        "promotion_gate": {
            "seed_registry_allowed": qa["pass"],
            "final_spatial_template_requires": [
                "Viewer_or_Ruby_dimension_QA",
                "collision_clearance_QA",
                "rights_QA",
                "Drive_RESULT_ACK_readback_x2",
            ],
            "metadata_only_promotion_forbidden": True,
        },
    }


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("manifest", type=Path)
    ap.add_argument("--out", type=Path, default=None)
    args = ap.parse_args()

    manifest = load_json(args.manifest)
    out_dir = args.out or args.manifest.parent
    bundle = build(manifest, args.manifest)

    dump_json(out_dir / "seed_bundle.json", bundle)
    dump_json(out_dir / "prompt_bundle.json", bundle["prompt_bundle"])
    dump_json(
        out_dir / "template_payload.json",
        {
            "model_id": bundle["model_id"],
            "templates": bundle["output_templates"],
            "estimate_rules": bundle["estimate_rules"],
            "created_at": bundle["created_at"],
        },
    )
    receipt = {
        "ok": bundle["manifest_qa"]["pass"],
        "builder_version": VERSION,
        "model_id": bundle["model_id"],
        "seed_count": len(bundle["seeds"]),
        "files": ["seed_bundle.json", "prompt_bundle.json", "template_payload.json"],
        "qa": bundle["manifest_qa"],
        "created_at": bundle["created_at"],
    }
    dump_json(out_dir / "seed_builder_receipt.json", receipt)
    print(json.dumps(receipt, ensure_ascii=False))
    return 0 if receipt["ok"] else 2


if __name__ == "__main__":
    raise SystemExit(main())
