var META_SIGNAL_LINEAGE_V1={version:'META_SIGNAL_LINEAGE_V1_20260911',spreadsheetId:'1C_CznU1Uo7dk-gKay3-oH8wFxutsGMlz27RSrbdVQwI',tz:'Asia/Seoul',projects:['CONTENTS_OS','NOTEBOOKLM','INTERIOR','TRAVEL','VTUBE']};
function metaSigBook_(){return SpreadsheetApp.openById(META_SIGNAL_LINEAGE_V1.spreadsheetId);}
function metaSigNow_(){return Utilities.formatDate(new Date(),META_SIGNAL_LINEAGE_V1.tz,"yyyy-MM-dd HH:mm:ss 'KST'");}
function metaSigHash_(s){return Utilities.base64EncodeWebSafe(Utilities.computeDigest(Utilities.DigestAlgorithm.SHA_256,String(s||''))).replace(/=+$/,'').slice(0,12).toUpperCase();}
function metaSigHeaders_(sh){return sh.getRange(1,1,1,sh.getLastColumn()).getDisplayValues()[0].map(String);}
function metaSigAppend_(sh,obj){var h=metaSigHeaders_(sh),row=new Array(h.length).fill('');h.forEach(function(k,i){if(Object.prototype.hasOwnProperty.call(obj,k))row[i]=obj[k];});sh.appendRow(row);return sh.getLastRow();}
function metaSigFind_(sh,idField,id){var h=metaSigHeaders_(sh),c=h.indexOf(idField)+1;if(c<1||sh.getLastRow()<2)return 0;var f=sh.getRange(2,c,sh.getLastRow()-1,1).createTextFinder(String(id)).matchEntireCell(true).findNext();return f?f.getRow():0;}
function validateMetaSignalV1_(x){x=x||{};var cls=String(x.sourceClass||'').toUpperCase();var allowed=['META_AD_LIBRARY_PUBLIC','META_BRANDED_CONTENT_PUBLIC','OWNED_META_METRICS'];var miss=[];['keyword','locale','sourceUrl','signal','confidence'].forEach(function(k){if(!String(x[k]||'').trim())miss.push(k);});if(allowed.indexOf(cls)<0)miss.push('sourceClass');return{ok:miss.length===0,missing:miss,sourceClass:cls};}
function ingestMetaSignalV1(x){var v=validateMetaSignalV1_(x);if(!v.ok)return{ok:false,error:'META_SIGNAL_SCHEMA_INVALID',missing:v.missing};var ss=metaSigBook_(),sh=ss.getSheetByName('62_TREND_RESEARCH_WAREHOUSE');var id='META_'+metaSigHash_(v.sourceClass+'|'+x.keyword+'|'+x.locale+'|'+x.sourceUrl+'|'+x.signal);var hit=metaSigFind_(sh,'RESEARCH_ID',id);if(hit)return{ok:true,deduped:true,row:hit,id:id};var status=v.sourceClass==='OWNED_META_METRICS'?'OWNED_METRIC_SIGNAL_ONLY':'VERIFIED_PUBLIC_SOURCE_SIGNAL_ONLY';var row=metaSigAppend_(sh,{RESEARCH_ID:id,COLLECTED_AT:metaSigNow_(),PLATFORM:v.sourceClass,DOMAIN:String(x.domain||'ALL_PROJECTS/META_MARKET_SIGNAL'),KEYWORD:String(x.keyword),LOCALE:String(x.locale),TITLE:String(x.title||'Meta public market signal'),CREATOR:'META_OFFICIAL_OR_OWNED',SOURCE_URL:String(x.sourceUrl),SUMMARY:String(x.summary||''),TREND_SIGNAL:String(x.signal),TREND_SCORE:String(x.score||''),APP_IMPACT:String(x.appImpact||'ALL_PROJECTS'),PLATFORM_IMPACT:'FACEBOOK;INSTAGRAM;THREADS_WHERE_APPLICABLE',RECOMMENDED_ACTION:String(x.action||'CROSS_EVIDENCE_BEFORE_QUEENS'),CONFIDENCE:String(x.confidence),STATUS:status});return{ok:true,deduped:false,row:row,id:id,status:status};}
function ensureMetaProjectTemplatesV1(){var ss=metaSigBook_(),sh=ss.getSheetByName('77_TEMPLATE_EVOLUTION_FACTORY'),made=[];META_SIGNAL_LINEAGE_V1.projects.forEach(function(p){var id='EVOLVE_META_SIGNAL_'+p+'_V1';if(metaSigFind_(sh,'EVOLVE_ID',id))return;metaSigAppend_(sh,{EVOLVE_ID:id,TRIGGER:'new GitHub requirement or scheduled market-research refresh',INPUT_RESULT:'Meta public/owned evidence object validated by ingestMetaSignalV1',MEASURE:'source provenance;keyword;locale;time;signal class;confidence;cross-evidence',BEST_COMPONENTS:'META_AD_LIBRARY_PUBLIC;META_BRANDED_CONTENT_PUBLIC;OWNED_META_METRICS',WEAK_COMPONENTS:'no general organic Meta trend ranking without approved source',NEW_TEMPLATE:p+'_T2_META_SIGNAL_ADAPTER_V1',SOURCE_PACKS:'62_TREND_RESEARCH_WAREHOUSE+75/77 Workflow Pack V2',REPO_PATCH:'none unless project contract requires adapter call',APPS_SCRIPT_PATCH:'reuse ingestMetaSignalV1',API_DELTA:'NO_NEW_OAUTH;NO_NEW_PAID_API',PROMOTION_GATE:'SIGNAL_ONLY→cross-evidence→Queens candidate→Seed after normal gates',REGRESSION:'never map Meta signal to Google Trends score; no direct Seed/Production promotion',WRITEBACK:'31/62/63/75/77/93 + project lineage',STATUS:'ACTIVE_SAFE_INTERNAL',VERSION:META_SIGNAL_LINEAGE_V1.version,OWNER:'CENTRAL_AGENT',NOTES:'Project='+p+'; new repo may clone this closest passing adapter.'});made.push(id);});return{ok:true,made:made,count:made.length};}
function bootstrapMetaSignalLineageV1(){var source=ingestMetaSignalV1({sourceClass:'META_AD_LIBRARY_PUBLIC',keyword:'PROJECT_SPECIFIC_KEYWORD_QUERY',locale:'ko-KR/global',sourceUrl:'https://www.facebook.com/ads/library/',title:'Meta Ad Library public market-signal capability',summary:'Meta public Ad Library can expose currently running ads; this row records source capability only, not general organic popularity.',signal:'META_PUBLIC_AD_MARKET_SOURCE_AVAILABLE_NOT_ORGANIC_TREND',confidence:'HIGH_SOURCE_CAPABILITY_ONLY',action:'Use project keyword evidence only after actual search readback; cross-check before Queens.'});var templates=ensureMetaProjectTemplatesV1();return{ok:source.ok&&templates.ok,source:source,templates:templates,version:META_SIGNAL_LINEAGE_V1.version,at:metaSigNow_()};}
function testMetaSignalLineageV1X2(){var a=bootstrapMetaSignalLineageV1(),b=bootstrapMetaSignalLineageV1();var ok=a.ok&&b.ok&&b.source.deduped===true&&b.templates.count===0;var ss=metaSigBook_(),ev=ss.getSheetByName('93_RUNTIME_EVIDENCE_CONTROL');metaSigAppend_(ev,{EVIDENCE_ID:'EVID_META_SIG_X2_'+metaSigHash_(metaSigNow_()),PROJECT_ID:'P00_AGENT_CORE',APP_ID:'ALL_PROJECTS',FUNCTION_OR_ROUTE:'testMetaSignalLineageV1X2',RUN_ID:'META_SIG_X2_'+metaSigHash_(JSON.stringify([a,b])),DRIVE_ACK:'62+77_WRITEBACK_READBACK_REQUIRED',PASS_1:a.ok?'PASS':'FAIL',PASS_2:ok?'PASS':'FAIL',LAST_GOOD:'WORKFLOW_PACK_V2_VERSION_12',STATUS:ok?'PASS_X2':'FAIL_X2_SEARCH_LEARN',ROOT_CAUSE:ok?'NONE':'DEDUPE_OR_TEMPLATE_IDEMPOTENCY',MIN_FIX:'MINIMUM_DIFF_ONLY',NEXT_RESUME_POINT:ok?'PROJECT_SIGNAL_INGESTION':'SEARCH_LEARN_RETEST',UPDATED_AT:metaSigNow_()});return{ok:ok,run1:a,run2:b,version:META_SIGNAL_LINEAGE_V1.version};}
function maybeRunMetaSignalLineageBootstrapOnceV1_(){var p=PropertiesService.getScriptProperties(),k='META_SIGNAL_LINEAGE_V1_X2_DONE';if(p.getProperty(k)==='1')return{ok:true,skipped:true,reason:'ALREADY_X2_PASS'};var r=testMetaSignalLineageV1X2();if(r.ok)p.setProperty(k,'1');return r;}
