const CAF_V4_VERSION='CENTRAL_DRIVE_ALL_FILE_INTAKE_V4_TAXONOMY_BRIDGE_20260903';
const CAF_V4_MASTER='1C_CznU1Uo7dk-gKay3-oH8wFxutsGMlz27RSrbdVQwI';
const CAF_V4_RUNTIME='DRIVE_ALL_FILE_SEED_RUNTIME';
const CAF_V4_QUEENS_QUEUE='14_QUEENS_RESEARCH_QUEUE';
const CAF_V4_QUEENS_RESULTS='37_QUEENS_RESEARCH_RESULTS';
const CAF_V4_CATALOG='81_ALL_FILE_CATALOG';
const CAF_V4_TAXONOMY='85_FILE_TYPE_TAXONOMY';
const CAF_V4_BRIDGES='86_DRIVE_RUNTIME_BRIDGE_ROUTER';
const CAF_V4_TASK='Q_DRIVE_ALL_FILE_AUTO';
const CAF_V4_BATCH=40;
const CAF_V4_BUDGET_MS=45000;

function runCentralDriveAllFileIntakeV4FromFactory(forceRun){
  const force=forceRun===true,now=new Date(),props=PropertiesService.getScriptProperties();
  const due='CAF_V4_DUE_'+Utilities.formatDate(now,'Asia/Seoul','yyyyMMddHH')+Math.floor(Number(Utilities.formatDate(now,'Asia/Seoul','m'))/10);
  if(!force&&props.getProperty('CAF_V4_LAST_DUE')===due)return{ok:true,skipped:true,reason:'SAME_10M_BUCKET',version:CAF_V4_VERSION};
  const lock=LockService.getScriptLock();if(!lock.tryLock(1000))return{ok:true,skipped:true,reason:'LOCKED',version:CAF_V4_VERSION};
  const started=Date.now();
  try{
    const ss=SpreadsheetApp.openById(CAF_V4_MASTER),runtime=cafV4Runtime_(ss),q=ss.getSheetByName(CAF_V4_QUEENS_QUEUE),qr=ss.getSheetByName(CAF_V4_QUEENS_RESULTS),cat=ss.getSheetByName(CAF_V4_CATALOG),taxSh=ss.getSheetByName(CAF_V4_TAXONOMY),brSh=ss.getSheetByName(CAF_V4_BRIDGES);
    if(!q||!qr||!cat||!taxSh||!brSh)throw new Error('CAF_V4_REQUIRED_SHEET_MISSING');
    const tax=cafV4Tax_(taxSh),routes=cafV4Routes_(brSh),catIdx=cafV4CatalogIndex_(cat),runId='DRIVEINTAKE4_'+Utilities.formatDate(now,'Asia/Seoul','yyyyMMdd_HHmmss_SSS');
    cafV4UpsertMerge_(q,'QUEENS_TASK_ID',CAF_V4_TASK,{QUEENS_TASK_ID:CAF_V4_TASK,APP_ID:'ALL_APPS',RESEARCH_TYPE:'DRIVE_FILE_AUTO_CLASSIFY',QUERY:'all accessible Drive files/folders→81/85/86→37 Queens→content QA→35 Seed',MARKET_ID:'INTERNAL',LOCALE_ID:'multi',PERIOD:'continuous',LIMIT:String(CAF_V4_BATCH),SOURCE_PROVIDER:'GOOGLE_DRIVE_INTERNAL',PRIORITY:'P0',STATUS:'READY',UPDATED_AT:now.toISOString()});
    let p=0,u=0,f=0,folders=0;
    let fileIt=cafV4FileIterator_(props),filesDone=false;
    while(fileIt.hasNext()&&p+u+f<CAF_V4_BATCH&&Date.now()-started<CAF_V4_BUDGET_MS){const x=fileIt.next();try{const r=cafV4IntakeEntry_(x,false,{now,runId,runtime,qr,cat,catIdx,tax,routes});if(r.unchanged)u++;else p++;}catch(e){f++;cafV4Fail_(runtime,runId,x,e,false);}}
    if(fileIt.hasNext())props.setProperty('CAF_V4_FILE_TOKEN',fileIt.getContinuationToken());else{props.deleteProperty('CAF_V4_FILE_TOKEN');filesDone=true;}
    if(filesDone&&p+u+f<CAF_V4_BATCH&&Date.now()-started<CAF_V4_BUDGET_MS){let folderIt=cafV4FolderIterator_(props);while(folderIt.hasNext()&&p+u+f<CAF_V4_BATCH&&Date.now()-started<CAF_V4_BUDGET_MS){const x=folderIt.next();try{const r=cafV4IntakeEntry_(x,true,{now,runId,runtime,qr,cat,catIdx,tax,routes});if(r.unchanged)u++;else{p++;folders++;}}catch(e){f++;cafV4Fail_(runtime,runId,x,e,true);}}if(folderIt.hasNext())props.setProperty('CAF_V4_FOLDER_TOKEN',folderIt.getContinuationToken());else props.deleteProperty('CAF_V4_FOLDER_TOKEN');}
    cafV4UpsertMerge_(q,'QUEENS_TASK_ID',CAF_V4_TASK,{LAST_RUN_AT:new Date().toISOString(),RESULT_COUNT:String(p),ERROR:f?'FAILED_COUNT='+f:'',UPDATED_AT:new Date().toISOString()});
    if(!force)props.setProperty('CAF_V4_LAST_DUE',due);
    return{ok:f===0,runId,processed:p,unchanged:u,failed:f,folders,seedPromoted:0,policy:'QUEENS_FIRST_CONTENT_QA_REQUIRED',version:CAF_V4_VERSION};
  }finally{lock.releaseLock();}
}

function cafV4IntakeEntry_(x,isFolder,c){
  if(cafV4Safe_(()=>x.isTrashed(),false))return{unchanged:true};
  const id=x.getId(),name=String(x.getName()||''),mime=isFolder?'application/vnd.google-apps.folder':String(x.getMimeType()||'application/octet-stream'),updated=cafV4Safe_(()=>x.getLastUpdated(),c.now),created=cafV4Safe_(()=>x.getDateCreated(),null),updatedIso=updated&&updated.toISOString?updated.toISOString():'',sig=cafV4Hash_(id+'|'+(updated&&updated.getTime?updated.getTime():updatedIso));
  const old=cafV4CatalogRecord_(c.cat,c.catIdx,id);if(old&&String(old.NOTES||'').indexOf('CAF_V4_SIG='+sig)>=0)return{unchanged:true};
  const t=cafV4Classify_(mime,name,old,c.tax,isFolder),route=cafV4Route_(t,old,c.routes),dataId=String(old&&old.DATA_ID||'')||'DATA-DRIVE-'+cafV4Hash_(id),url=isFolder?cafV4Safe_(()=>x.getUrl(),'https://drive.google.com/drive/folders/'+id):'https://drive.google.com/open?id='+encodeURIComponent(id),project=cafV4Project_(name,mime),qres='QRES_DRIVE_'+cafV4Hash_(id+'|'+updatedIso+'|QRES'),nowIso=new Date().toISOString();
  const rights=String(old&&old.RIGHTS_CLASS||t.rights||'REVIEW_REQUIRED'),sens=String(old&&old.SENSITIVITY||t.sensitivity||'UNKNOWN');
  cafV4UpsertMerge_(c.qr,'RESULT_ID',qres,{RESULT_ID:qres,QUEENS_TASK_ID:CAF_V4_TASK,APP_ID:'ALL_APPS',RESEARCH_TYPE:'DRIVE_'+t.fileClass,QUERY:'FILE_ID='+id+';NAME='+name+';MIME='+mime+';PROJECT='+project+';ROUTE='+route.routeId,SOURCE_PROVIDER:'GOOGLE_DRIVE_INTERNAL',SOURCE_TITLE:name,SOURCE_URL:url,SOURCE_PUBLISHED_AT:created&&created.toISOString?created.toISOString():'',COLLECTED_AT:nowIso,MARKET_ID:'INTERNAL',LOCALE_ID:'multi',EVIDENCE_STATUS:'METADATA_INDEXED_CONTENT_QA_REQUIRED',SEED_STATUS:'QA_PENDING_CONTENT_EXTRACTION',SOURCE_HASH:'META_'+sig,NOTES:'FILE_ID='+id+';DATA_ID='+dataId+';TYPE_ID='+t.typeId+';FILE_CLASS='+t.fileClass+';PROJECT_ID='+project+';ROUTE='+route.routeId+';TEMPLATE='+route.template+';RIGHTS='+rights+';SENSITIVITY='+sens+';NO_METADATA_ONLY_SEED=TRUE'});
  const note=cafV4AppendNote_(String(old&&old.NOTES||''),'CAF_V4_SIG='+sig+';QRES='+qres+';ROUTE='+route.routeId);
  cafV4CatalogUpsert_(c.cat,c.catIdx,id,{FILE_RECORD_ID:String(old&&old.FILE_RECORD_ID||'')||'FILE-AUTO-'+cafV4Hash_(id),DRIVE_FILE_ID:id,TITLE:name,MIME_TYPE:mime,EXTENSION:cafV4Ext_(name,mime,isFolder),FILE_CLASS:String(old&&old.FILE_CLASS||'')||t.fileClass,BUSINESS_ROLE:String(old&&old.BUSINESS_ROLE||'')||t.businessRole,APP_SCOPE:String(old&&old.APP_SCOPE||'')||'ALL_APPS',DATA_ID:dataId,PARENT_OR_GROUP:String(old&&old.PARENT_OR_GROUP||'')||cafV4Parent_(x),DRIVE_URL:url,SIZE_BYTES:isFolder?'':cafV4Size_(x),CREATED_AT:String(old&&old.CREATED_AT||'')||(created&&created.toISOString?created.toISOString():''),UPDATED_AT:updatedIso,CONTENT_HASH:String(old&&old.CONTENT_HASH||'')||'METADATA_SIG_'+sig,RIGHTS_CLASS:rights,SENSITIVITY:sens,CANONICAL_STATUS:String(old&&old.CANONICAL_STATUS||'')||'CANDIDATE',DUPLICATE_GROUP:String(old&&old.DUPLICATE_GROUP||''),USAGE_MODES:String(old&&old.USAGE_MODES||'')||t.usage,LINKED_FUNCTION_IDS:cafV4Pipe_(String(old&&old.LINKED_FUNCTION_IDS||''),'runCentralDriveAllFileIntakeV4FromFactory'),LINKED_TRIGGER_IDS:cafV4Pipe_(String(old&&old.LINKED_TRIGGER_IDS||''),'TRG_DRIVE_ALL_FILE_SEED_REUSE_20260903'),REVIEW_STATE:String(old&&old.REVIEW_STATE||'')||'AUTO_CLASSIFIED_CONTENT_QA_PENDING',NOTES:note});
  cafV4RuntimeWrite_(c.runtime,{runId:c.runId,checkedAt:nowIso,fileId:id,fileName:name,mimeType:mime,lastUpdated:updatedIso,sizeBytes:isFolder?'':cafV4Size_(x),dataClass:t.fileClass,projectId:project,queensStatus:'QUEENS_REGISTERED',seedStatus:'QA_PENDING_CONTENT_EXTRACTION',seedId:'',templateRoute:route.template,bridgeRoute:route.routeId,dedupKey:id+'|'+updatedIso,result:'QUEENS_REGISTERED_PENDING_SEED_QA',ack:'ACK',driveReadback:'PASS',retryState:'WAIT_CONTENT_EVIDENCE',error:'',sourceUrl:url,workflowId:'ORCH_DRIVE_ALL_FILE_SEED_V1',runtimeState:'FACTORY_LOGICAL_QA_GATE',notes:'QRES='+qres+';DATA_ID='+dataId+';TYPE_ID='+t.typeId+';RIGHTS='+rights+';SENSITIVITY='+sens});
  if(typeof centralPublishDataEvent==='function'){try{centralPublishDataEvent({producer_app_id:'APP_AGENT_CORE',data_stage:'QUEENS',entity_type:t.fileClass,entity_id:qres,summary:name,source_url:url,lineage_ids:[id,dataId,qres],consumer_scope:['ALL_APPS'],status:'QA_PENDING',readback_status:'PASS',memo:route.routeId});}catch(_){}}
  return{unchanged:false,qres,dataId,route:route.routeId};
}

function cafV4Tax_(sh){const v=sh.getDataRange().getDisplayValues(),o={};if(v.length<2)return o;const h=cafV4Header_(v[0]);for(let i=1;i<v.length;i++){const r=v[i],id=String(r[h.TYPE_ID]||'');if(!id)continue;o[id]={typeId:id,fileClass:String(r[h.FILE_CLASS]||'OTHER'),businessRole:String(r[h.DEFAULT_BUSINESS_ROLE]||'UNCLASSIFIED'),usage:String(r[h.DEFAULT_USAGE]||'HOLD_REVIEW'),rights:String(r[h.DEFAULT_RIGHTS_GATE]||'REVIEW_REQUIRED'),sensitivity:String(r[h.DEFAULT_SENSITIVITY]||'UNKNOWN'),qa:String(r[h.QA_RULE]||'')};}return o;}
function cafV4Routes_(sh){const v=sh.getDataRange().getDisplayValues(),o={};if(v.length<2)return o;const h=cafV4Header_(v[0]);for(let i=1;i<v.length;i++){const r=v[i],id=String(r[h.ROUTE_ID]||'');if(id)o[id]={routeId:id,status:String(r[h.RUNTIME_STATUS]||''),qa:String(r[h.QA_GATE]||'')};}return o;}
function cafV4Classify_(mime,name,old,tax,isFolder){const s=(mime+' '+name).toLowerCase();let id='FT_OTHER';if(isFolder||/google-apps\.folder/.test(mime))id='FT_FOLDER';else if(/google-apps\.spreadsheet|\.xlsx?$|\.csv$/i.test(s))id='FT_SHEET';else if(/google-apps\.presentation|\.pptx?$|\.odp$/i.test(s))return Object.assign({},tax.FT_DOC||{},{typeId:'FT_DOC',fileClass:'SLIDE',businessRole:'PRESENTATION|BRIEF|TEMPLATE',usage:'REFERENCE|STRUCTURE|TEMPLATE'});else if(/google-apps\.document|\.docx?$|\.txt$|\.md$/i.test(s))id='FT_DOC';else if(/application\/pdf|\.pdf$/i.test(s))id='FT_PDF';else if(/image\//i.test(mime)||/\.(jpg|jpeg|png|webp|gif|heic)$/i.test(name))id='FT_IMAGE';else if(/video\//i.test(mime)||/\.(mp4|mov|webm|mkv|avi)$/i.test(name))id='FT_VIDEO';else if(/audio\//i.test(mime)||/\.(wav|mp3|m4a|aac|flac|ogg)$/i.test(name))id='FT_AUDIO';else if(/\.skp$/i.test(name)||/_skp|sketchup/i.test(s))id='FT_SKETCHUP';else if(/\.(zip|rar|7z|tar|gz)$/i.test(name))id='FT_ARCHIVE';else if(/\.(js|ts|tsx|gs|py|json|ya?ml|html|css|md)$/i.test(name)||/javascript|json|yaml|text\/plain/i.test(mime))id='FT_CODE_JSON';const t=Object.assign({typeId:id,fileClass:'OTHER',businessRole:'UNCLASSIFIED',usage:'HOLD_REVIEW',rights:'REVIEW_REQUIRED',sensitivity:'UNKNOWN'},tax[id]||{});t.typeId=id;if(id==='FT_AUDIO'&&old&&old.FILE_CLASS)t.fileClass=String(old.FILE_CLASS);return t;}
function cafV4Route_(t,old,routes){const fc=String(t.fileClass||'OTHER').toUpperCase(),known=String(old&&old.BUSINESS_ROLE||'').toUpperCase();let id='RT_OTHER_REVIEW';if(/^(SHEET|DOC|SLIDE)$/.test(fc))id='RT_SHEET_DOC';else if(fc==='IMAGE')id='RT_IMAGE';else if(fc==='VIDEO')id='RT_VIDEO';else if(fc==='SKETCHUP_3D')id='RT_SKETCHUP';else if(fc==='PDF'||fc==='ARCHIVE')id='RT_PDF_ARCHIVE';else if(t.typeId==='FT_AUDIO'){if(/IR|REVERB|SPATIAL/.test(known))id='RT_AUDIO_IR';else if(/VOICE|TTS|NARRATION|AUDIOBOOK/.test(known))id='RT_AUDIO_VOICE';else id='RT_AUDIO_CLASSIFY';}else if(fc==='CODE_TEXT')id='RT_CODE_TEXT';else if(fc==='FOLDER')id='RT_FOLDER_INDEX';return{routeId:id,template:cafV4Template_(fc),route:routes[id]||{}};}
function cafV4Template_(fc){return({SHEET:'DATA_TABLE_SEED_TEMPLATE',DOC:'DOC_KNOWLEDGE_SEED_TEMPLATE',SLIDE:'SLIDE_STRUCTURE_SEED_TEMPLATE',IMAGE:'IMAGE_PACK_SEED_TEMPLATE',VIDEO:'VIDEO_ANALYSIS_SEED_TEMPLATE',AUDIO:'AUDIO_ROLE_CLASSIFY_SEED_TEMPLATE',AUDIO_IR_EFFECTS:'AUDIO_IR_ASSET_SEED_TEMPLATE',SKETCHUP_3D:'SKETCHUP_3D_ASSET_SEED_TEMPLATE',PDF:'PDF_EVIDENCE_SEED_TEMPLATE',ARCHIVE:'ARCHIVE_MANIFEST_SEED_TEMPLATE',CODE_TEXT:'CODE_WORKFLOW_SEED_TEMPLATE',FOLDER:'FOLDER_RECURSIVE_INDEX_TEMPLATE',OTHER:'GENERAL_ASSET_SEED_TEMPLATE'})[fc]||'GENERAL_ASSET_SEED_TEMPLATE';}

function cafV4CatalogIndex_(sh){const o={},last=sh.getLastRow();if(last<2)return o;const v=sh.getRange(2,2,last-1,1).getDisplayValues();for(let i=0;i<v.length;i++){const id=String(v[i][0]||'');if(id)o[id]=i+2;}return o;}
function cafV4CatalogRecord_(sh,idx,id){const row=idx[id];if(!row)return null;const h=sh.getRange(1,1,1,sh.getLastColumn()).getDisplayValues()[0],v=sh.getRange(row,1,1,h.length).getDisplayValues()[0],o={_row:row};h.forEach((x,i)=>o[String(x)]=v[i]);return o;}
function cafV4CatalogUpsert_(sh,idx,id,obj){const h=sh.getRange(1,1,1,sh.getLastColumn()).getDisplayValues()[0],hi=cafV4Header_(h),rowNo=idx[id],row=rowNo?sh.getRange(rowNo,1,1,h.length).getValues()[0]:new Array(h.length).fill('');Object.keys(obj).forEach(k=>{if(hi[k]!==undefined)row[hi[k]]=obj[k];});if(rowNo)sh.getRange(rowNo,1,1,h.length).setValues([row]);else{sh.appendRow(row);idx[id]=sh.getLastRow();}}
function cafV4UpsertMerge_(sh,key,keyValue,obj){if(!sh)throw new Error('SHEET_MISSING');const h=sh.getRange(1,1,1,sh.getLastColumn()).getDisplayValues()[0],hi=cafV4Header_(h),kc=hi[key];if(kc===undefined)throw new Error('KEY_HEADER_MISSING:'+key+':'+sh.getName());let rowNo=0;if(sh.getLastRow()>=2){const cell=sh.getRange(2,kc+1,sh.getLastRow()-1,1).createTextFinder(String(keyValue)).matchEntireCell(true).findNext();if(cell)rowNo=cell.getRow();}const row=rowNo?sh.getRange(rowNo,1,1,h.length).getValues()[0]:new Array(h.length).fill('');Object.keys(obj).forEach(k=>{if(hi[k]!==undefined)row[hi[k]]=obj[k];});if(rowNo)sh.getRange(rowNo,1,1,h.length).setValues([row]);else sh.appendRow(row);return rowNo||sh.getLastRow();}
function cafV4Runtime_(ss){let sh=ss.getSheetByName(CAF_V4_RUNTIME);if(!sh)sh=ss.insertSheet(CAF_V4_RUNTIME);const h=['RUN_ID','CHECKED_AT','FILE_ID','FILE_NAME','MIME_TYPE','LAST_UPDATED','SIZE_BYTES','DATA_CLASS','PROJECT_ID','QUEENS_STATUS','SEED_STATUS','SEED_ID','TEMPLATE_ROUTE','BRIDGE_ROUTE','DEDUP_KEY','RESULT','ACK','DRIVE_READBACK','RETRY_STATE','ERROR','SOURCE_URL','WORKFLOW_ID','RUNTIME_STATE','NOTES'];if(sh.getLastRow()===0)sh.getRange(1,1,1,h.length).setValues([h]);return sh;}
function cafV4RuntimeWrite_(sh,x){const row=[x.runId,x.checkedAt,x.fileId,x.fileName,x.mimeType,x.lastUpdated,x.sizeBytes,x.dataClass,x.projectId,x.queensStatus,x.seedStatus,x.seedId,x.templateRoute,x.bridgeRoute,x.dedupKey,x.result,x.ack,x.driveReadback,x.retryState,x.error,x.sourceUrl,x.workflowId,x.runtimeState,x.notes];sh.appendRow(row);}
function cafV4Fail_(sh,runId,x,e,isFolder){try{cafV4RuntimeWrite_(sh,{runId,checkedAt:new Date().toISOString(),fileId:cafV4Safe_(()=>x.getId(),''),fileName:cafV4Safe_(()=>x.getName(),''),mimeType:isFolder?'application/vnd.google-apps.folder':cafV4Safe_(()=>x.getMimeType(),''),lastUpdated:'',sizeBytes:'',dataClass:'ERROR',projectId:'AUTO',queensStatus:'FAILED',seedStatus:'FAILED',seedId:'',templateRoute:'',bridgeRoute:'',dedupKey:'',result:'FAILED',ack:'NO_ACK',driveReadback:'FAIL',retryState:'RETRY_NEXT_WAKE',error:String(e&&e.message||e),sourceUrl:'',workflowId:'ORCH_DRIVE_ALL_FILE_SEED_V1',runtimeState:'DEGRADED',notes:'V4 intake failure preserved; no Seed promotion.'});}catch(_){}}
function cafV4FileIterator_(p){const t=p.getProperty('CAF_V4_FILE_TOKEN');try{return t?DriveApp.continueFileIterator(t):DriveApp.getFiles();}catch(_){p.deleteProperty('CAF_V4_FILE_TOKEN');return DriveApp.getFiles();}}
function cafV4FolderIterator_(p){const t=p.getProperty('CAF_V4_FOLDER_TOKEN');try{return t?DriveApp.continueFolderIterator(t):DriveApp.getFolders();}catch(_){p.deleteProperty('CAF_V4_FOLDER_TOKEN');return DriveApp.getFolders();}}
function cafV4Project_(n,m){const s=(n+' '+m).toLowerCase();if(/travel|여행/.test(s))return'P07_TRAVEL';if(/interior|인테리어|견적/.test(s))return'P06_HOMEDESIGN';if(/youtube|content|analyzer|seed/.test(s))return'P01_RESEARCH';if(/notebook|flow|video|image|audio|voice/.test(s))return'P03_MEDIA';if(/food|먹방|kfood/.test(s))return'P09_FOOD';return'P00_AGENT_CORE';}
function cafV4Ext_(n,m,f){if(f)return'FOLDER';if(/google-apps\.spreadsheet/.test(m))return'GSHEET';if(/google-apps\.document/.test(m))return'GDOC';if(/google-apps\.presentation/.test(m))return'GSLIDE';const x=String(n||'').match(/\.([A-Za-z0-9]{1,10})$/);return x?x[1].toLowerCase():'';}
function cafV4Parent_(x){try{const it=x.getParents();return it.hasNext()?it.next().getId():'';}catch(_){return'';}}
function cafV4Size_(x){try{return x.getSize();}catch(_){return'';}}
function cafV4Header_(h){const o={};h.forEach((x,i)=>o[String(x)]=i);return o;}
function cafV4Hash_(s){const d=Utilities.computeDigest(Utilities.DigestAlgorithm.SHA_256,String(s));return d.slice(0,10).map(b=>('0'+((b+256)%256).toString(16)).slice(-2)).join('').toUpperCase();}
function cafV4AppendNote_(a,b){a=String(a||'');return a.indexOf(b)>=0?a:(a?a+' | ':'')+b;}
function cafV4Pipe_(a,b){const p=String(a||'').split('|').filter(Boolean);if(p.indexOf(b)<0)p.push(b);return p.join('|');}
function cafV4Safe_(fn,d){try{return fn();}catch(_){return d;}}

function testCentralDriveAllFileIntakeV4ForceX2(){const a=runCentralDriveAllFileIntakeV4FromFactory(true),b=runCentralDriveAllFileIntakeV4FromFactory(true);return{ok:a&&a.ok!==false&&b&&b.ok!==false,first:a,second:b,version:CAF_V4_VERSION};}
