const DRIVE_JSON_BACKEND_URL = process.env.CONTENT_OS_CACHE_BACKEND_URL || 'https://script.google.com/macros/s/AKfycbzz247_Mwl9c6N1WxmpHAttwHQJB6RCFtaY08XlHgxysz1iEzg7HWDXa3i5oXhDS1jo/exec';
const PUBLIC_SCOPE = 'SHARED_PUBLIC';
const PUBLIC_KEY_PREFIX = 'contentos:public-';
const PUBLIC_RIGHTS = new Set(['YOUTUBE_PUBLIC_METADATA', 'PUBLIC_METADATA']);
const parseJson = (text: string) => { try { return JSON.parse(text); } catch { return null; } };
const requestHeader = (req: any, name: string) => { const value = req.headers?.[name.toLowerCase()]; return Array.isArray(value) ? String(value[0] || '') : String(value || ''); };
const isTrustedServerRequest = (req: any) => { const expected = String(process.env.CONTENT_OS_FRONT_JSON_SERVER_TOKEN || ''); if (!expected) return false; const supplied = requestHeader(req, 'x-content-os-front-token'); return supplied.length === expected.length && supplied === expected; };
const isSharedPublicKey = (storeKey: string) => String(storeKey || '').startsWith(PUBLIC_KEY_PREFIX);
const isAllowedPublicWrite = (payload: any) => { const storeKey = String(payload?.store_key || ''); const scope = String(payload?.user_scope_hash || ''); const rights = String(payload?.rights_class || ''); const secret = String(payload?.secret_yn || 'N').toUpperCase(); return isSharedPublicKey(storeKey) && scope === PUBLIC_SCOPE && PUBLIC_RIGHTS.has(rights) && secret !== 'Y'; };
async function postBackend(action: string, payload: any) { const headers: Record<string, string> = { 'Content-Type': 'application/json' }; const token = process.env.CONTENT_OS_BACKEND_TOKEN; if (token) headers['X-Content-OS-Token'] = token; const response = await fetch(DRIVE_JSON_BACKEND_URL, { method: 'POST', headers, body: JSON.stringify({ action, payload, source: 'content-os-front-json' }), redirect: 'follow' }); const text = await response.text(); return { response, json: parseJson(text) }; }
export default async function handler(req: any, res: any) { res.setHeader('Cache-Control', 'no-store'); const trusted = isTrustedServerRequest(req); if (req.method === 'GET') { const storeKey = String(req.query?.store_key || ''); if (!storeKey) return res.status(400).json({ ok: false, hit: false, error: 'STORE_KEY_REQUIRED' }); if (!trusted && !isSharedPublicKey(storeKey)) return res.status(403).json({ ok: false, hit: false, error: 'PRIVATE_DRIVE_JSON_REQUIRES_AUTHENTICATED_SERVER' }); try { const { response, json } = await postBackend('front.json.get.v3', { store_key: storeKey }); if (!response.ok || !json) return res.status(200).json({ ok: true, hit: false, backend: 'DRIVE_JSON_PENDING' }); if (!trusted && json?.hit && String(json?.user_scope_hash || '') !== PUBLIC_SCOPE) return res.status(403).json({ ok: false, hit: false, error: 'PRIVATE_DRIVE_JSON_REQUIRES_AUTHENTICATED_SERVER' }); return res.status(200).json(json); } catch { return res.status(200).json({ ok: true, hit: false, backend: 'DRIVE_JSON_PENDING' }); } } if (req.method !== 'POST') return res.status(405).json({ ok: false, error: 'METHOD_NOT_ALLOWED' }); const action = String(req.body?.action || 'upsert'); const payload = req.body?.payload || {}; if (!payload.store_key) return res.status(400).json({ ok: false, error: 'STORE_KEY_REQUIRED' }); if (action === 'remove' && !trusted) return res.status(403).json({ ok: false, mirrored: false, error: 'DRIVE_JSON_REMOVE_REQUIRES_TRUSTED_SERVER' }); if (action !== 'remove' && !trusted && !isAllowedPublicWrite(payload)) return res.status(403).json({ ok: false, mirrored: false, error: 'PRIVATE_DRIVE_JSON_REQUIRES_AUTHENTICATED_SERVER' }); const backendAction = action === 'remove' ? 'front.json.remove.v3' : 'front.json.upsert.v3'; try { const { response, json } = await postBackend(backendAction, payload); if (!response.ok || !json || json.ok === false) return res.status(202).json({ ok: true, mirrored: false, backend: 'DRIVE_JSON_PENDING' }); return res.status(200).json({ ok: true, mirrored: true, ...json }); } catch { return res.status(202).json({ ok: true, mirrored: false, backend: 'DRIVE_JSON_PENDING' }); } }
