const APPS_SCRIPT_URL = process.env.CONTENT_OS_CACHE_BACKEND_URL || 'https://script.google.com/macros/s/AKfycbzz247_Mwl9c6N1WxmpHAttwHQJB6RCFtaY08XlHgxysz1iEzg7HWDXa3i5oXhDS1jo/exec';
const WRITER_URL = process.env.DRYWRITER_WEBAPP_URL || 'https://script.google.com/macros/s/AKfycbxNPNmtCEeIjLJuUnfp-sTdEgQOzUUA_2cMkyqCzhaUJcRvYwppBgtSuPjbezWCn2zKrw/exec';
const FORCE_ALLOWED = new Set([
  'contentos.runtime.identity.v3','contentos.runtime.register.v3','contentos.drive.cache.selftest.v3','front.json.selftest.v3','contentos.intelligence.selftest.v3','contentos.pipeline.recovery.v3',
  'drywriter.writer.health.a','drywriter.writer.health.b','drywriter.writer.list.a','drywriter.writer.list.b','drywriter.writer.get.a','drywriter.writer.get.b','drywriter.writer.save.a','drywriter.writer.save.b'
]);
const parseJson=(text:string)=>{try{return JSON.parse(text);}catch{return null;}};
const RECORDS:any={
  a:{contentId:'CONTENT_552644ff-2d03-47ff-b3bd-6cab021650fe',title:'Full AI Workflow for Interior Designers – From Brief to Pro Render (2026)',rawText:'제목: Full AI Workflow for Interior Designers – From Brief to Pro Render (2026)\n\n구성: {"hook":"2026 live YouTube API verified current source; AI interior brief→render→video workflow demand signal. Reference-only evidence for factory Queens→Seed→T1/T2 recovery.","problem":"Full AI Workflow for Interior Designers – From Brief to Pro Render (2026)","evidence":"https://www.youtube.com/watch?v=Wt6IzAS71e0","solution":"practical steps","close":"question"}\n\n출처: ["https://www.youtube.com/watch?v=Wt6IzAS71e0"]',summary:'2026 AI 인테리어 브리프→렌더→영상 워크플로우 수요 분석 T2 결과',category:'INTERIOR_AI',tags:['AI','인테리어','YouTube','ContentOS'],coverImageUrl:'https://i.ytimg.com/vi/Wt6IzAS71e0/hqdefault.jpg',coverPrompt:'Reference-only YouTube thumbnail; do not treat as generated asset.',sourceId:'SRC_YT_AI_INTERIOR_WT6_20260903_1132',templateId:'CONTENTOS_FACTORY_T2_20260903',personaId:'PERSONA_CONTENTOS_ANALYZER',formId:'SPEC_REALITY_ESSAY',writingSeedId:'SEED_078df7c3-89d6-4601-8727-aa18f85a8daf',status:'READY',language:'ko',createdAt:'2026-09-03T02:44:07.988Z',updatedAt:'2026-09-03T03:24:00.000Z'},
  b:{contentId:'CONTENT_27948d09-6bc5-4003-9afb-50c04bf8b69f',title:'BEST AI TOOLS Interior Designer MUST USE in 2026',rawText:'제목: BEST AI TOOLS Interior Designer MUST USE in 2026\n\n구성: {"hook":"2026 live YouTube API verified current source; interior AI tools/visualization/productivity comparison demand signal. Reference-only evidence for x2 factory recovery.","problem":"BEST AI TOOLS Interior Designer MUST USE in 2026","evidence":"https://www.youtube.com/watch?v=M-1PRSwo3A4","solution":"practical steps","close":"question"}\n\n출처: ["https://www.youtube.com/watch?v=M-1PRSwo3A4"]',summary:'2026 인테리어 AI 도구·시각화·생산성 비교 수요 분석 T2 결과',category:'INTERIOR_AI',tags:['AI','인테리어','도구','YouTube','ContentOS'],coverImageUrl:'https://i.ytimg.com/vi/M-1PRSwo3A4/hqdefault.jpg',coverPrompt:'Reference-only YouTube thumbnail; do not treat as generated asset.',sourceId:'SRC_YT_AI_INTERIOR_M1P_20260903_1132',templateId:'CONTENTOS_FACTORY_T2_20260903',personaId:'PERSONA_CONTENTOS_ANALYZER',formId:'SPEC_REALITY_ESSAY',writingSeedId:'SEED_8ed080a2-0e96-4b3b-8b1f-4863a5e548df',status:'READY',language:'ko',createdAt:'2026-09-03T02:44:13.631Z',updatedAt:'2026-09-03T03:24:00.000Z'}
};
async function request(target:string,init:any={}){const r=await fetch(target,{redirect:'follow',...init});const text=await r.text();const json=parseJson(text);return{ok:r.ok&&(!json||json.ok!==false),upstreamStatus:r.status,upstreamContentType:r.headers.get('content-type')||'',finalUrl:r.url,json,textPreview:json?undefined:text.slice(0,1800)};}
function writerGet(action:string,extra:any={}){const u=new URL(WRITER_URL);u.searchParams.set('action',action);Object.entries(extra).forEach(([k,v])=>u.searchParams.set(k,String(v)));return request(u.toString());}
function writerPost(body:any){return request(WRITER_URL,{method:'POST',headers:{'Content-Type':'text/plain;charset=utf-8'},body:JSON.stringify(body)});}
export default async function handler(req:any,res:any){res.setHeader('Cache-Control','no-store');const forceAction=String(req.query?.forceAction||'').trim();if(forceAction){res.setHeader('X-Content-OS-Diagnostic','IMMEDIATE_RUNTIME_FORCE_20260903');if(!FORCE_ALLOWED.has(forceAction))return res.status(400).json({ok:false,error:'ACTION_NOT_ALLOWED',forceAction});try{
  if(forceAction==='drywriter.writer.health.a'||forceAction==='drywriter.writer.health.b'){const result=await writerGet('HEALTH');return res.status(200).json({ok:result.ok,action:forceAction,target:'WRITER_CONTENT_FACTORY_V001',...result,at:new Date().toISOString()});}
  if(forceAction==='drywriter.writer.list.a'||forceAction==='drywriter.writer.list.b'){const result=await writerGet('LIST_CONTENT',{pageSize:5});return res.status(200).json({ok:result.ok,action:forceAction,target:'WRITER_CONTENT_FACTORY_V001',...result,at:new Date().toISOString()});}
  const key=forceAction.endsWith('.a')?'a':'b';const record=RECORDS[key];
  if(forceAction.startsWith('drywriter.writer.get.')){const result=await writerGet('GET_CONTENT',{contentId:record.contentId});return res.status(200).json({ok:result.ok,action:forceAction,target:'WRITER_CONTENT_FACTORY_V001',contentId:record.contentId,...result,at:new Date().toISOString()});}
  if(forceAction.startsWith('drywriter.writer.save.')){const result=await writerPost({action:'SAVE_CONTENT',record:{...record,expectedUpdatedAt:record.updatedAt}});return res.status(200).json({ok:result.ok,action:forceAction,target:'WRITER_CONTENT_FACTORY_V001',contentId:record.contentId,...result,at:new Date().toISOString()});}
  const headers:Record<string,string>={'Content-Type':'application/json'};const token=process.env.CONTENT_OS_BACKEND_TOKEN;if(token)headers['X-Content-OS-Token']=token;const result=await request(APPS_SCRIPT_URL,{method:'POST',headers,body:JSON.stringify({action:forceAction,source:'production-health-force-20260903'})});return res.status(200).json({ok:result.ok,action:forceAction,...result,at:new Date().toISOString()});
}catch(e:any){return res.status(502).json({ok:false,action:forceAction,error:String(e?.message||e),at:new Date().toISOString()});}}
const qstBackendConfigured=Boolean(process.env.CONTENT_OS_BACKEND_URL||process.env.CENTRAL_INTELLIGENCE_BACKEND_URL);return res.status(200).json({ok:true,service:'content-os',version:'2026.8.31',canonicalRepo:'8friend8ship-cloud/contents-os-git',canonicalBranch:'main',runtimeMirrorRepo:'8friend8ship-cloud/Analyzer-12.09',qstBackendConfigured,storedBackdataFallbackConfigured:true,backendConfigured:qstBackendConfigured,backendService:qstBackendConfigured?'QST_BACKEND':'COMMON_LIBRARY_COLLECTOR',backendMode:qstBackendConfigured?'live-qst-env':'stored-backdata-canonical',storageMode:'local-first-central-mirror-enabled',readMode:qstBackendConfigured?'qst-plus-stored-fallback':'stored-backdata-only',completionGate:'RUNTIME_OUTPUT_X2_AND_LESSON_CHECKED',at:new Date().toISOString()});}
