const APPS_SCRIPT_URL = process.env.CONTENT_OS_CACHE_BACKEND_URL || 'https://script.google.com/macros/s/AKfycbzz247_Mwl9c6N1WxmpHAttwHQJB6RCFtaY08XlHgxysz1iEzg7HWDXa3i5oXhDS1jo/exec';
const WRITER_URL = process.env.DRYWRITER_WEBAPP_URL || 'https://script.google.com/macros/s/AKfycbxNPNmtCEeIjLJuUnfp-sTdEgQOzUUA_2cMkyqCzhaUJcRvYwppBgtSuPjbezWCn2zKrw/exec';
const FORCE_ALLOWED = new Set([
  'contentos.runtime.identity.v3','contentos.runtime.register.v3','contentos.drive.cache.selftest.v3','front.json.selftest.v3','contentos.intelligence.selftest.v3','contentos.pipeline.recovery.v3',
  'drywriter.writer.health.a','drywriter.writer.health.b','drywriter.writer.generate.a','drywriter.writer.generate.b'
]);
const parseJson = (text:string) => { try { return JSON.parse(text); } catch { return null; } };
const WRITER_GENERATE:any = {
  'drywriter.writer.generate.a': {action:'GENERATE_DRY_WRITER_MASTER',input:{inputId:'DRY_af359c03-fd27-41c2-aefa-92ed9c55fe71',appId:'APP_ANALYZER',personaId:'PERSONA_CONTENTOS_ANALYZER',sourceId:'SRC_YT_AI_INTERIOR_WT6_20260903_1132',seedId:'SEED_078df7c3-89d6-4601-8727-aa18f85a8daf',topic:'Full AI Workflow for Interior Designers – From Brief to Pro Render (2026)',queensRawIds:['SRC_YT_AI_INTERIOR_WT6_20260903_1132'],queensClusterIds:['CONTENTOS_20260903_INTERIOR_AI'],sourceIds:['SRC_YT_AI_INTERIOR_WT6_20260903_1132'],primarySourceIds:['SRC_YT_AI_INTERIOR_WT6_20260903_1132'],factClaims:[{claim:'Source is a current 2026 YouTube interior AI workflow reference.',sourceId:'SRC_YT_AI_INTERIOR_WT6_20260903_1132',sourceDate:'2026-09-03'}],dataUsageContract:{dataUsageStatus:'PASS',dataUsagePolicyVersion:'CENTRAL_API_FREE_REFERENCE_ONLY'},writingSpecId:'SPEC_REALITY_ESSAY',locale:'ko-KR'},probe_request_id:'DRY_af359c03-fd27-41c2-aefa-92ed9c55fe71'},
  'drywriter.writer.generate.b': {action:'GENERATE_DRY_WRITER_MASTER',input:{inputId:'DRY_eac8bce4-de95-479f-8640-a5109cac25ab',appId:'APP_ANALYZER',personaId:'PERSONA_CONTENTOS_ANALYZER',sourceId:'SRC_YT_AI_INTERIOR_M1P_20260903_1132',seedId:'SEED_8ed080a2-0e96-4b3b-8b1f-4863a5e548df',topic:'BEST AI TOOLS Interior Designer MUST USE in 2026',queensRawIds:['SRC_YT_AI_INTERIOR_M1P_20260903_1132'],queensClusterIds:['CONTENTOS_20260903_INTERIOR_AI_B'],sourceIds:['SRC_YT_AI_INTERIOR_M1P_20260903_1132'],primarySourceIds:['SRC_YT_AI_INTERIOR_M1P_20260903_1132'],factClaims:[{claim:'Source is a current 2026 YouTube interior AI tools reference.',sourceId:'SRC_YT_AI_INTERIOR_M1P_20260903_1132',sourceDate:'2026-09-03'}],dataUsageContract:{dataUsageStatus:'PASS',dataUsagePolicyVersion:'CENTRAL_API_FREE_REFERENCE_ONLY'},writingSpecId:'SPEC_REALITY_ESSAY',locale:'ko-KR'},probe_request_id:'DRY_eac8bce4-de95-479f-8640-a5109cac25ab'}
};
async function postJson(target:string, body:any, headers:Record<string,string> = {}) {const upstream=await fetch(target,{method:'POST',headers:{'Content-Type':'application/json',...headers},body:JSON.stringify(body),redirect:'follow'});const text=await upstream.text();const json=parseJson(text);return {ok:upstream.ok&&(!json||json.ok!==false),upstreamStatus:upstream.status,upstreamContentType:upstream.headers.get('content-type')||'',finalUrl:upstream.url,json,textPreview:json?undefined:text.slice(0,1600)};}
export default async function handler(req:any,res:any){res.setHeader('Cache-Control','no-store');const forceAction=String(req.query?.forceAction||'').trim();if(forceAction){res.setHeader('X-Content-OS-Diagnostic','IMMEDIATE_RUNTIME_FORCE_20260903');if(!FORCE_ALLOWED.has(forceAction))return res.status(400).json({ok:false,error:'ACTION_NOT_ALLOWED',forceAction});try{if(forceAction==='drywriter.writer.health.a'||forceAction==='drywriter.writer.health.b'){const result=await postJson(WRITER_URL,{action:'HEALTH',probe:forceAction,source:'central_immediate_writer_health_20260903'});return res.status(200).json({ok:result.ok,action:forceAction,target:'WRITER_CONTENT_FACTORY_V001',...result,at:new Date().toISOString()});}if(WRITER_GENERATE[forceAction]){const body=WRITER_GENERATE[forceAction];const result=await postJson(WRITER_URL,body);return res.status(200).json({ok:result.ok,action:forceAction,target:'WRITER_CONTENT_FACTORY_V001',requestId:body.probe_request_id,...result,at:new Date().toISOString()});}const headers:Record<string,string>={};const token=process.env.CONTENT_OS_BACKEND_TOKEN;if(token)headers['X-Content-OS-Token']=token;const result=await postJson(APPS_SCRIPT_URL,{action:forceAction,source:'production-health-force-20260903'},headers);return res.status(200).json({ok:result.ok,action:forceAction,...result,at:new Date().toISOString()});}catch(e:any){return res.status(502).json({ok:false,action:forceAction,error:String(e?.message||e),at:new Date().toISOString()});}}
const qstBackendConfigured=Boolean(process.env.CONTENT_OS_BACKEND_URL||process.env.CENTRAL_INTELLIGENCE_BACKEND_URL);return res.status(200).json({ok:true,service:'content-os',version:'2026.8.31',canonicalRepo:'8friend8ship-cloud/contents-os-git',canonicalBranch:'main',runtimeMirrorRepo:'8friend8ship-cloud/Analyzer-12.09',qstBackendConfigured,storedBackdataFallbackConfigured:true,backendConfigured:qstBackendConfigured,backendService:qstBackendConfigured?'QST_BACKEND':'COMMON_LIBRARY_COLLECTOR',backendMode:qstBackendConfigured?'live-qst-env':'stored-backdata-canonical',storageMode:'local-first-central-mirror-enabled',readMode:qstBackendConfigured?'qst-plus-stored-fallback':'stored-backdata-only',completionGate:'RUNTIME_OUTPUT_X2_AND_LESSON_CHECKED',at:new Date().toISOString()});}
